language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t romach007/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true romach007/client-test npm test

after_success:
  - docker build -t romach007/multi-client ./client
  - docker build -t romach007/multi-nginx ./nginx
  - docker build -t romach007/multi-server ./server
  - docker build -t romach007/multi-worker ./worker
  # Log in to the Docker CLI
  - echo "$DOCKER_KEY" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to Docker Hub
  - docker push romach007/multi-client
  - docker push romach007/multi-nginx
  - docker push romach007/multi-server
  - docker push romach007/multi-worker